refactor(cc-matomo-info)!: rework properties to avoid impossible states
CleverCloud/clever-components pull request #1055
Opened 2024-05-07 14:13 UTC by florian-sanders-cc

## What does this PR do?

- Refactors the `cc-matomo-info` component to implement our new state structure,
- Implements TypeChecking within the `cc-matomo-info` component and its stories.

## How to review?

- Check the commit (the diff may not be easy to read so you can review the final result locally if you prefer),
- If you check it locally, you should not get any Typescript error within the component file or the story file,
- Compare the [prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-addon-cc-matomo-info--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-matomo-info/state-migration/index.html?path=/story/%F0%9F%9B%A0-addon-cc-matomo-info--default-story).

2024-05-13 12:32 UTC, pdesoyres-cc requested changes
Well done. I have just some minor nitpicks.

2024-05-13 13:29 UTC, florian-sanders-cc commented on src/templates/cc-link/cc-link.js
> + * @typedef {import('lit').TemplateResult<1>} TemplateResult
Definitely, we forgot about this, thanks! :wink:

2024-05-13 13:30 UTC, florian-sanders-cc commented on src/templates/cc-link/cc-link.js
>  function isDifferentOrigin (rawUrl) {
This will be done in a different PR because several components rely on this one. Thanks for pointing it out :wink:

2024-05-23 15:35 UTC, roberttran-cc approved these changes

2024-05-30 12:00 UTC, pdesoyres-cc approved these changes
LGTM

2024-06-12 10:11 UTC, merged