feat(cc-logs-application-view): enhance filtering
CleverCloud/clever-components pull request #1083
Opened 2024-06-13 13:12 UTC by pdesoyres-cc

### what this PR do ?

- adds the ability to filter with a regex
- adds the ability to filter with an exact string

Fixes #1073
Fixes #1014

### how to text

Use the sandbox to test the features.

2024-06-13 16:25 UTC, hsablonniere requested changes
This is so nice and elegant, I like the icons. I create a few notes, nothing much. Well done @pdesoyres-cc !!!! :clap:

2024-06-14 07:07 UTC, pdesoyres-cc commented on test/regex-parse.test.js
> +  });
I was wondering too so I went for the less strict solution.

2024-06-14 07:08 UTC, pdesoyres-cc commented on src/lib/regex-parse.js
> +  const match = input.match(/(\/?)(.+)\1([a-z]*)/i);
nice, I like that

2024-06-14 07:12 UTC, pdesoyres-cc commented on src/lib/regex-parse.js
> +    .join('');
Could be nice, but the `RegExp` constructor fails when passing invalid flags.

2024-06-17 14:59 UTC, florian-sanders-cc approved these changes
I think the feature looks good and it works well from what I've tested.

Gg :sunglasses:

2024-06-18 09:19 UTC, roberttran-cc approved these changes
LGTM! Very neat PR.

A few non-blocking suggestion/question/feedback.

2024-06-18 09:34 UTC, HeleneAmouzou approved these changes
I did the review with @roberttran-cc , apart from the comments he left, LGTM !

2024-06-18 10:02 UTC, pdesoyres-cc commented on test/regex-parse.test.js
> +  it('should be greedy on slash', () => {
I wanted to make sure that a path with multiple slashes is taken into the expression group

2024-06-18 13:19 UTC, pdesoyres-cc commented on src/components/cc-logs-application-view/cc-logs-application-view.js
> + * @typedef {import('../cc-logs/cc-logs.types.js').LogFilter} LogFilter
you're right

2024-06-19 10:26 UTC, merged