Docs: Add ADR about Type Checking
CleverCloud/clever-components pull request #1286
Opened 2024-12-17 15:55 UTC by florian-sanders-cc

## What does this PR do?

- Adds an ADR about Type Checking.

2025-01-07 15:26 UTC, roberttran-cc requested changes
Great ADR!

A couple small corrections to make. :wink:

2025-01-07 15:26 UTC, roberttran-cc commented on docs/adr/adr-0027-enabling-type-checking.md
> +- Find a way to upgrade the TypeScript version when we want (lit labs analyzer)
**🎯 suggestion:**

```suggestion
- Find a way to upgrade the TypeScript version when we want
```

2025-01-07 15:26 UTC, roberttran-cc commented on docs/adr/adr-0027-enabling-type-checking.md
> +  - This should be possible if we move from `custom-elements-manifest/analyzer` & `lit-analyzer` to `@lit-labs/analyzer` but this is not trivial as explained in [Investigate @lit-labs/analyzer usage
**🔨 issue:**

```suggestion
  - This should be possible if we move from `custom-elements-manifest/analyzer` & `lit-analyzer` to `@lit-labs/analyzer` but this is not trivial as explained in [Investigate @lit-labs/analyzer usage - issue #1156 - Clever Components repository](https://github.com/CleverCloud/clever-components/issues/1156).
```

2025-01-08 10:59 UTC, HeleneAmouzou approved these changes
LGTM ! :clap:  Nothing more to add than the comments @roberttran-cc already made !

2025-01-08 13:55 UTC, hsablonniere approved these changes
Great ADR!!! :clap: 

> - The build step is only here to optimize the code of the components.

Not sure if we really want to but there's an opportunity to mention bare imports. Our source files need a bundling phase to handle such bare imports. Nowadays, they could work as is but with import maps.

Include a note about this if you think it's relevant :wink:

2025-01-08 15:37 UTC, Galimede approved these changes
The ADR is great, GG Florian! :muscle: 

I have maybe a small suggestion, we do refer to some tools like `lit-analyzer` or `CEM`, maybe we could add a section with a link to these projects or add a link directly where they are first mentioned? :thinking:

2025-01-09 09:47 UTC, pdesoyres-cc approved these changes
LGTM. Well done Florian.

2025-01-10 10:55 UTC, florian-sanders-cc commented
@Galimede 

> I have maybe a small suggestion, we do refer to some tools like lit-analyzer or CEM, maybe we could add a section with a link to these projects or add a link directly where they are first mentioned? 🤔

Good idea! I chose to add direct links to the projects within the sentences instead of adding a separate section

2025-01-10 11:42 UTC, merged