Add <cc-jenkins-info> component
CleverCloud/clever-components pull request #299
Opened 2021-08-03 14:04 UTC by BlackYoup

This PR adds a new component, named `<cc-jenkins-info>` with its smart definition.

This component will be used to display some information about a Jenkins add-on like the documentation link, the link to the Jenkins UI and some information about available updates.

This PR also bumps the `@clevercloud/client` dependency to `^7.6.0` as we need a new endpoint released in that version for the smart component.

Fix #272

2021-08-03 14:16 UTC, BlackYoup commented
Here the preview link: https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-jenkins-info/index.html?path=/story/%F0%9F%9B%A0-addon-cc-jenkins-info--default-story

2021-08-04 22:53 UTC, hsablonniere requested changes

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> + * 🎨 default CSS display: `block`
The CSS display now has a dedicated custom `@cssdisplay` JSDoc tag.

* Remove this line and add this line before the `@prop`:

```
 * @cssdisplay block
```

You can see an example in https://github.com/CleverCloud/clever-components/blob/master/docs/cc-example-component.js#L46

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> + * 🧐 [component's source code on GitHub](https://github.com/CleverCloud/clever-components/blob/master/src/addon/cc-jenkins-info.js)
This is no longer needed. The documentation generation does this automatically now :tada:

As you can see in the example, no need for this anymore: https://github.com/CleverCloud/clever-components/blob/master/docs/cc-example-component.js#L22-L24

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> + *
This is no longer needed. The documentation generation does this automatically now :tada: 

As you can see in the example, no need for this anymore: master/docs/cc-example-component.js

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> + * @prop {Boolean} error - Display an error message.
We don't have an automated way to do this yet but please sort props alphabetically (just put error first).

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> +      error: { type: Boolean, attribute: 'error' },
We don't have an automated way to do this yet but please sort props alphabetically (just put error first).

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> +      error: { type: Boolean, attribute: 'error' },
You don't need to specify the `attribute` when the property is a single word.

It's mentioned in the example: https://github.com/CleverCloud/clever-components/blob/master/docs/cc-example-component.js#L68-L69

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> +    const versions = this.versions || {};
We can now use the modern and better syntax for this:

```
const versions = this.versions ?? {};
```

2021-08-04 22:53 UTC, hsablonniere commented on src/addon/cc-jenkins-info.js
> +import '../atoms/cc-flex-gap.js';
Seems like you're not using any cc-flex-gap in here.

2021-08-04 22:53 UTC, hsablonniere commented on stories/addon/cc-jenkins-info.stories.js
> +});
We often put the error story between skeleton and data loaded.

This is in the stories example: https://github.com/CleverCloud/clever-components/blob/master/docs/cc-example-component.stories.js#L37-L63

2021-08-04 22:53 UTC, hsablonniere commented on stories/addon/cc-jenkins-info.stories.js
> +export const dataLoaded = makeStory(conf, {
Could be renamed into `dataLoadedWithSameVersions`.

This will be displayed as **Data loaded (same versions)** in Storybook.

2021-08-04 22:53 UTC, hsablonniere commented on stories/addon/cc-jenkins-info.stories.js
> +export const updateAvailable = makeStory(conf, {
Could be renamed into `dataLoadedWithDifferentVersions`.

This will be displayed as **Data loaded (different versions)** in Storybook.

2021-08-05 09:00 UTC, BlackYoup commented
@hsablonniere thanks for the review, I addressed your comments :)

2021-08-05 21:40 UTC, hsablonniere commented
@BlackYoup I resolved the clonflicts and removed an empty line in JSDoc ;-)

2021-08-05 21:40 UTC, merged