all-form-controls: add support and story for horizontal form layout
CleverCloud/clever-components pull request #448
Opened 2022-05-02 17:39 UTC by florian-sanders-cc

Fixes #446 

- Added a new section in the `all-form-controls` story to showcase all form controls horizontally aligned with help messages below each form control.
- Specified line-height on the `<label>` (`cc-input-*` + `cc-select`)/ `<legend>` (`cc-toggle`) element of all the form controls.
- Aligned all the form controls from top (`align-items: start`).
- Added a margin variable in `defaultThemeStyles` to be used as `margin-top` value on a `cc-button` so that it is aligned with the rest of form controls (specifies an offset equal to `label` height (line-height + padding = `1.6em` )
- Added small paragraph to try and explain all of this inside the new section of the story.

2022-05-02 17:41 UTC, florian-sanders-cc commented on src/styles/default-theme.js
> +    --margin-top-btn-horizontal-form: 1.6em;
really not sure about this naming :roll_eyes:

2022-05-04 13:14 UTC, hsablonniere requested changes

2022-05-04 13:14 UTC, hsablonniere commented on stories/atoms/all-form-controls.js
> +    defaultThemeStyles,
The `css` used by `makeStory` expects a string, it is directly used under the hood to create a `<style>` tag. It doesn't work like lit so the array doesn't work and the result of lit's `css` function doesn't work either.

2022-05-04 13:14 UTC, hsablonniere commented on stories/atoms/all-form-controls.js
> +    defaultThemeStyles,
```
defaultThemeStyles.toString(),
```

```
[
/* ... */
].join('\n'),
```

2022-05-04 14:49 UTC, merged