refactor: update the state and use the new smart definition system for TCP redirections
CleverCloud/clever-components pull request #574
Opened 2022-09-22 07:52 UTC by hsablonniere

2022-10-04 13:53 UTC, pdesoyres-cc requested changes
nice!

2022-10-04 13:53 UTC, pdesoyres-cc commented on src/components/cc-tcp-redirection/cc-tcp-redirection.types.d.ts
> +  state: 'loading';
we use double quotes in types.d.ts files

2022-10-04 13:53 UTC, pdesoyres-cc commented on src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.types.d.ts
> +  state: 'loading';
we use double quotes in types.d.ts files

2022-10-04 13:53 UTC, pdesoyres-cc commented on src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.smart.js
> +          notifyError(component, i18n('cc-tcp-redirection-form.create.error', { namespace }));
add console.error

2022-10-04 13:53 UTC, pdesoyres-cc commented on src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.smart.js
> +          notifyError(component, i18n('cc-tcp-redirection-form.delete.error', { namespace }));
add console.error

2022-10-05 08:36 UTC, hsablonniere commented
@pdesoyres-cc Thanks for your feedbacks. It updated the PR :wink:

2022-10-14 09:14 UTC, florian-sanders-cc approved these changes
LGTM :+1: Gg

2022-10-17 12:30 UTC, merged