feat(cc-notice): init new component
CleverCloud/clever-components pull request #622
Opened 2022-11-09 13:16 UTC by Galimede

preview here: https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-notice/index.html?path=%2Fstory%2F%F0%9F%A7%AC-atoms-cc-notice--default-story

2022-11-09 14:32 UTC, hsablonniere commented
## Review

* :+1: I like the colors and icons and the design of the props.
* :thinking: I wonder if the title should also be a slot, maybe useful if we want to add some `em` or `code` but probably overkill and not needed for now. We can try this the day we feel it's necessary.
* I'm not about sure about the left/right spacing with `no-icon`.
* I'm not about sure about the spacing between the icon and the message with no heading.
* Should we adapt the color of the hover background for the closeable button?

:clap: Really nice work

* Can we add a commit in this PR to use this in the `cc-warning-payment`?
* Can we also try what some component would look like with a `cc-notice intent="warning"` instead of a cc-error?

2022-11-17 11:52 UTC, roberttran-cc commented
Overall design (colors, props, etc.) is really nice, GG! Looking forward to see them in our other components! :heart_eyes_cat: 

Some minor feedback:
- white-space between title and content could be slightly reduced
- white-space between icon and content in the "No Heading" story could be increased
- the close button interactive zone could use more padding
- it could be nice to have stories with large content, to check on the wrapping and leading

On a more global note (that may be discussed synchronously):
- the "Custom Message" story is nice but too close to the "Default" story and with much more white-space: consider reducing white-space in the slotted content? or maybe go all-in on slotting and use another component (for example `<cc-env-var-create>`)?
- the "No Heading" story alignment between the icon and the content seems off but... image/text alignment is [hard on the web](https://iamvdo.me/blog/css-avance-metriques-des-fontes-line-height-et-vertical-align) (and not sure if it still seems off with multi-line content)
- overall, I think we could use concrete text in the stories, to close the gap (CSS joke lmao) between the component in their stories and in their real world usage

2022-11-17 13:48 UTC, pdesoyres-cc commented
I like the overall design.

* Could we try with smaller margins?
* Could we have the close button more in the top right corner and with same top and right distance from the edge?
* Could we try less space between title and message?

2022-11-25 15:27 UTC, florian-sanders-cc requested changes
:clap: Gg @Galimede and thanks a lot for handling the update of design token names.
It was annoying to do but very necessary :+1: 

I think this component looks great, I like the colors (:smirk:) and the spacing too :+1: 
The API seems easy to use which is all we want for an atom component !
Stories are great too.

I found very small details to adjust within the code and I just wonder if we could create a "long text + no heading", WDYT ?

2022-11-25 15:27 UTC, florian-sanders-cc commented on src/components/cc-notice/cc-notice.stories.js
> +  withOtherIcons,
Not really important but I think you are missing a few stories in there.

2022-11-25 15:27 UTC, florian-sanders-cc commented on src/components/cc-notice/cc-notice.js
> +      noIcon: { type: Boolean, attribute: 'no-icon', reflect: true },
I don't think we need to reflect most of the attributes now that we rely on a wrapper + class system.

It's still necessary for the intent I guess unless you want to make it rely on a class system like others.

2022-11-25 15:27 UTC, florian-sanders-cc commented on src/components/cc-warning-payment/cc-warning-payment.js
>   * @typedef {import('./cc-warning-payment.types.js').PaymentMethodError} PaymentMethodError
not related to this line but we need to update the doc about css display: 
```js
@cssdisplay block
```

2022-11-25 15:27 UTC, florian-sanders-cc commented on src/components/cc-warning-payment/cc-warning-payment.js
> +    const { title, error } = (this.mode === 'overview' || this.mode === 'billing') ? this._renderOrgaError(this.errors[0]) : '';
Not really related to your modifications but isn't `_renderOrgaError` essentially a method to return i18n strings that we usually name `_get...` ?

It does not seem to return anything to render so I wonder if the name is not misleading.

2022-11-25 15:27 UTC, florian-sanders-cc commented on src/components/cc-warning-payment/cc-warning-payment.js
> +
is this space now necessary for stylelint ? (I don't have any opinion about this, i'm fine with or without it :smile:)

2022-11-29 10:59 UTC, hsablonniere requested changes
This is really nice :+1:

I added a few details but it's almost ready for prime time!!! :tada:

2022-11-29 10:59 UTC, hsablonniere commented on src/components/cc-notice/cc-notice.js
> +      closeable: { type: String },
Isn't this a `Boolean` ?

2022-11-29 10:59 UTC, hsablonniere commented on src/components/cc-notice/cc-notice.stories.js
> +        <div slot="icon"><img src="http://placekitten.com/24/24" alt="placeholder kitten"/></div>
Can you add a style `display:block` on the `<img>`, it will remove the space below and align things correctly.

2022-11-29 10:59 UTC, hsablonniere commented on src/components/cc-warning-payment/cc-warning-payment.js
> +  _getOrgaError ({ type }) {
Since it's not a subrender function, can we move it between the constructor and the main render?

2022-11-29 14:13 UTC, pdesoyres-cc requested changes
Nice work!

I really like the UI. I find the margins and alignments really nice.

Don't forget to modify the 2 commit messages and add the `Fixes #xxx`: This will help the release-please bot to associate a link to the issue and the change log entry.

2022-11-29 14:13 UTC, pdesoyres-cc commented on src/components/cc-notice/cc-notice.js
> +
extra space here

2022-11-29 14:13 UTC, pdesoyres-cc commented on src/components/cc-notice/cc-notice.js
> +
extra space here

2022-11-29 15:06 UTC, pdesoyres-cc approved these changes

2022-11-29 15:40 UTC, hsablonniere approved these changes

2022-11-29 15:44 UTC, merged