fix(eslint): check for improper sanitize function usage
CleverCloud/clever-components pull request #723
Opened 2023-03-09 15:07 UTC by roberttran-cc

Fixes #718.

# What the PR does

Adds a check to the `eslint-rules/i18n-always-arrow-with-sanitize.js` es-lint rule. It detects and fixes improper usage of the `sanitize` function in translation files.

The detected patterns are the following:
```js
{
  'cc-example.pattern-1': ({ foo }) => sanitize(`<em >improper ${foo} usage number 1</em>`),
  'cc-example.pattern-2': ({ foo }) => {
    return sanitize(`<em >improper ${foo} usage number 2</em>`);
  },
}
```

And are fixed to:
```js
{
  'cc-example.pattern-1': ({ foo }) => sanitize`<em >improper ${foo} usage number 1</em>`,
  'cc-example.pattern-2': ({ foo }) => {
    return sanitize`<em >improper ${foo} usage number 2</em>`;
  },
}
```

Note the parentheses were removed.

# How to review

You can check the diff or checkout the branch and test locally as well. 

- Maybe the pattern detection can be improved.
- There are probably edge cases (see the "Limitations" paragraph below).
- Do not forget the wording on (CLI outputs).

# Limitations

Actually, there are more complex patterns that are not detected:

```js
{
  'cc-example.complex-1': ({ foo }) => {
    return foo
      ? sanitize(`<em >improper ${foo} complex usage number 1</em>`)
      : `bar`;
  },
  'cc-example.complex-2': ({ foo }) => {
    const foobar = sanitize(`<em >improper ${foo} complex usage number 2</em>`);
    return foo ? foobar : `bar`;
  },
}
```

And there are probably more other more complex undetected patterns (though they won't be usual).

:arrow_right: Should we consider them? WDYT?

# What's left to do

Rename the `eslint-rules/i18n-always-arrow-with-sanitize.js` filename to match accurately what it's testing: it was left unmodified for better diff readability.

2023-03-15 08:25 UTC, pdesoyres-cc requested changes
Well done @roberttran-cc!

I just have a few nitpicks.

2023-03-15 08:25 UTC, pdesoyres-cc commented on eslint-rules/i18n-always-template-literal-sanitize.js
> +    fix: (fixer) => {
doc: Could you add what this fix support and what it doesn't?

2023-03-15 14:23 UTC, Galimede approved these changes
GG @roberttran-cc! :clap:

2023-03-17 08:49 UTC, pdesoyres-cc approved these changes

2023-03-17 09:03 UTC, merged