feat(tokens): add `--cc-color-border-default` and use it when relevant
CleverCloud/clever-components pull request #736
Opened 2023-04-05 18:18 UTC by florian-sanders-cc

Fixes #733

2023-04-25 08:49 UTC, pdesoyres-cc reviewed
Nice work!

I just have a consideration on the variable naming.
Maybe it's just me, but I would prefer:

* --cc-color-border-neutral-strong
* --cc-color-border-neutral
* --cc-color-border-neutral-weak

2023-05-03 10:01 UTC, roberttran-cc approved these changes
LGTM, nice addition to our tokens!
And I agree with @pdesoyres-cc's suggestion. :ok_hand:

2023-05-04 14:34 UTC, hsablonniere approved these changes
Same as @pdesoyres-cc for the names but apart from that, LGTM :+1:

2023-05-05 09:33 UTC, pdesoyres-cc requested changes
LGTM apart from a nitpick about variables ordering in the default theme

2023-05-05 09:33 UTC, pdesoyres-cc commented on src/styles/default-theme.css
> +  /* Usage: for contrasted borders.
nitpick: Could we try to order the variables? Could be by thickness first. Or could be intent first.

2023-05-17 15:34 UTC, Galimede approved these changes

2023-05-17 17:58 UTC, merged