feat(cc-addon-admin): make use of the cc-notice instead of cc-error
CleverCloud/clever-components pull request #789
Opened 2023-06-22 13:33 UTC by Galimede

Fixes #777

2023-06-28 07:22 UTC, pdesoyres-cc requested changes
Well done! I just have one minor suggestion.

2023-06-28 07:22 UTC, pdesoyres-cc commented on src/components/cc-addon-admin/cc-addon-admin.js
>      const isFormDisabled = (this.error !== false) || this.saving;
nitpick: minor simplification

```suggestion
    const isFormDisabled = this.error || this.saving;
```

2023-06-28 09:13 UTC, florian-sanders-cc approved these changes
Gg @Galimede apart from a small nitpick (the usual one :joy:) it's all good!

2023-06-28 09:13 UTC, florian-sanders-cc commented on src/components/cc-addon-admin/cc-addon-admin.js
> +          <cc-notice intent="warning" .message="${i18n('cc-addon-admin.error-loading')}"></cc-notice>
**nitpick:** 
```suggestion
          <cc-notice intent="warning" message="${i18n('cc-addon-admin.error-loading')}"></cc-notice>
```

2023-06-28 15:51 UTC, hsablonniere approved these changes
:+1: All good for me, well done!

2023-06-29 16:14 UTC, roberttran-cc approved these changes
LGTM: perfect!

2023-07-03 15:40 UTC, merged