refactor(cc-invoice-list)!: migrate to the new smart component design
CleverCloud/clever-components pull request #930
Opened 2023-12-22 11:22 UTC by pdesoyres-cc

Fixes #922 

## What is this?

* new state design: no impossible state
* new smart: no RxJs
* add demo in demo-smart

## How to review?

* check code
* check for regression

2024-01-04 16:04 UTC, roberttran-cc approved these changes

2024-01-09 16:34 UTC, florian-sanders-cc requested changes
A very tiny nitpick but all good! 

Good job for the `renderView` thing, I was confused at first because we don't usually do this but it's smart :+1:

2024-01-09 16:34 UTC, florian-sanders-cc commented on src/components/cc-invoice-list/cc-invoice-list.types.d.ts
> +import {Invoice} from "../common.types";
**nitpick:** 
```suggestion
import { Invoice } from "../common.types";
```

2024-01-24 14:41 UTC, HeleneAmouzou approved these changes

2024-01-25 14:43 UTC, Galimede approved these changes
LGTM, GG! :muscle:

2024-01-29 14:26 UTC, roberttran-cc approved these changes

2024-02-02 18:06 UTC, merged