test: use resize-observer-errors utility from `@lit-labs/virtualizer`
CleverCloud/clever-components pull request #939
Opened 2024-01-10 10:22 UTC by pdesoyres-cc

Fixes #808

## What is it?

This PR replaces our code with the `@lit-labs/virtualizer` utility.

2024-01-17 14:18 UTC, hsablonniere requested changes
Thanks @pdesoyres-cc for this, :clap: :+1:

I put a small nitpick but it's OK for me.

2024-01-17 14:18 UTC, hsablonniere commented on test/helpers/accessibility.js
> +  before(() => (teardown = ignoreWindowOnError(messagePredicate)));
nitpick: can we put this assignment on its own line?

2024-01-18 17:33 UTC, hsablonniere approved these changes

2024-01-19 08:01 UTC, florian-sanders-cc approved these changes
Feels a lot cleaner this way!

Good job!

2024-01-19 08:27 UTC, merged